version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: team6-mongo-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27018:27017"
    volumes:
      - mongo_test_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 3s
      retries: 3

  provenance_test:
    build:
      context: ..
      dockerfile: tests/Dockerfile.test
    container_name: provenance-test
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

volumes:
  mongo_test_data:
